name: local-ci

on:
  # run tests on every push and PR…
  push:
  pull_request:

env:
  HA_VERSION: "2025.5.0"               # pin Home-Assistant core used for tests

jobs:
  # ───────────────────────── tests ──────────────────────────
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11"]               # HA ≥2025.2 requires Python 3.12

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install ".[test]" "homeassistant==${HA_VERSION}"

      - name: Run pytest + coverage gate
        run: |
          pytest -q \
            --cov=kronoterm_voice_actions \
            --cov-report=xml \
            --cov-fail-under=85

  # ──────────────────────── deploy ─────────────────────────
  deploy:
    if: github.ref == 'refs/heads/main'    # deploy **only** from main
    runs-on: [self-hosted, Linux, ARM]

    steps:
      - uses: actions/checkout@v4          # checkout same commit being deployed

      - name: Sync integration to HAOS
        run: |
          rsync -az src/kronoterm_voice_actions/ \
                haos:/config/custom_components/kronoterm_voice_actions/

      - name: Restart Home Assistant
        run: |
          ssh haos "/usr/bin/ha core restart"
