name: local-ci

on:
    push:
    pull_request:

env:
    HA_VERSION: "2025.5.3"

jobs:
    # ───────────────────────── matcher tests ──────────────────────────
    matcher_unit_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: ["3.13"]

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python }}

            - name: Install deps
              run: |
                  python -m pip install -U pip
                  pip install ".[test]" "homeassistant==${HA_VERSION}"

            - name: Run matcher unit tests + coverage gate
              run: |
                  pytest -v
    # ───────────────────────── target machine tests ──────────────────────────
    target_machine_tests:
        runs-on: [self-hosted, Linux, ARM]
        needs: matcher_unit_tests

        steps:
            - uses: actions/checkout@v4

            - name: Sync integration to HAOS
              run: |
                  rsync -az src/kronoterm_voice_actions/ \
                        haos:/config/custom_components/

            - name: Run integration tests
              run: |
                  ssh haos "cd config/ && python3 custom_components/runner.py"

    # ──────────────────────── deploy ─────────────────────────
    deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: [self-hosted, Linux, ARM]
        needs: matcher_unit_tests

        steps:
            - uses: actions/checkout@v4

            - name: Sync integration to HAOS
              run: |
                  rsync -az src/kronoterm_voice_actions/ \
                        haos:/config/custom_components/

            - name: Restart Home Assistant
              run: |
                  ssh haos "/usr/bin/ha core restart"
