name: local-ci

on:
    push:
    pull_request:

env:
    HA_VERSION: "0.42.4"

jobs:
    # ───────────────────────── unit tests ──────────────────────────
    unit_tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: ["3.11"]

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python }}

            - name: Install deps
              run: |
                  python -m pip install -U pip
                  pip install ".[test]" "homeassistant==${HA_VERSION}"

            - name: Run unit tests + coverage gate
              run: |
                  pytest -q \
                    -m "not target_machine" \  # Exclude tests marked with 'target_machine'
                    --cov=kronoterm_voice_actions \
                    --cov-report=xml \
                    --cov-fail-under=85

    # ───────────────────────── target machine tests ──────────────────────────
    target_machine_tests:
        runs-on: [self-hosted, Linux, ARM]
        needs: unit_tests

        steps:
            - uses: actions/checkout@v4

            - name: Sync integration to HAOS
              run: |
                  rsync -az test/ haos:/config/test/

            - name: Install dependencies on target
              run: |
                  # SSH into haos and install any necessary dependencies for the tests
                  ssh haos "pip install homeassistant==${HA_VERSION} pytest"

            - name: Run tests on target machine
              run: |
                  # SSH into haos and run pytest targeting the specific tests
                  ssh haos "cd config/test && pytest -q -m target_machine"

    # ──────────────────────── deploy ─────────────────────────
    deploy:
        if: github.ref == 'refs/heads/main'
        runs-on: [self-hosted, Linux, ARM]
        needs: target_machine_tests # Ensure target machine tests pass before deploying

        steps:
            - uses: actions/checkout@v4

            - name: Sync integration to HAOS
              run: |
                  rsync -az src/kronoterm_voice_actions/ \
                        haos:/config/custom_components/

            - name: Restart Home Assistant
              run: |
                  ssh haos "/usr/bin/ha core restart"
